apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: pajikos
  namespace: home-assistant
spec:
  interval: 5m0s
  url: http://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 10m
  timeout: 5m
  releaseName: home-assistant
  chart:
    spec:
      chart: home-assistant
      version: '0.2.116'
      sourceRef:
        kind: HelmRepository
        name: pajikos
  values:
    resources:
      requests:
        cpu: "200m"
        memory: "2G"
      limits:
        cpu: "500m"
        memory: "2G"
    initContainers:
      - name: init-hacs
        image: bash
        command: ["bash", "-c", "cd /config && wget -O - https://get.hacs.xyz | bash -"]
        volumeMounts:
          - mountPath: /config
            name: home-assistant
    ingress:
      enabled: true
    persistence:
      enabled: true
      existingVolume: home-assistant
      size: 10Gi
    configuration:
      enabled: true
      trusted_proxies:
        - 192.168.0.0/16
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
