apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    volume: home-assistant
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/home-assistant"