apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: logging
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logging-loki
  namespace: logging
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: loki
      version: '5.10.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
  values:
    ingester:
      chunk_encoding: snappy
    tracing:
      enabled: true
    querier:
      max_concurrent: 4
    deploymentMode: Distributed
    backend:
      persistence:
        selector:
          matchLabels:
            volume: loki
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      tsdb_shipper:
        active_index_directory: /var/lib/loki/data/tsdb-index
        cache_location: /var/lib/loki/data/tsdb-cache
        shared_store: filesystem
      filesystem:
        directory: /var/lib/loki/data
  releaseName: grafana-loki
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
