apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: logging
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: logging-loki
  namespace: logging
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: loki
      version: '5.10.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
  values:
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      commonStorageConfig:
        type: filesystem
      rulerConfig:
        storage:
          type: local
    singleBinary:
      replicas: 1
      persistence:
        storageClass: local-loki
        enabled: true
        size: 5Gi
    table_manager:
      retention_deletes_enabled: true
      retention_period: 24h
      releaseName: grafana-loki
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
