apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logging-config
  namespace: logging
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: home-flux
    namespace: flux-system
  path: "./clusters/home/logging/logging-config"
  prune: true
  timeout: 1m
