apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-db
spec:
  storageClassName: local-loki
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/loki"