apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: next-cloud
spec:
  interval: 5m0s
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: next-cloud
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: nextcloud
      version: '6.3.0'
      sourceRef:
        kind: HelmRepository
        name: next-cloud
  values:
    nextcloud:
      host: nextcloud.blrobinson.uk
      username: admin
      password: changeme
      existingSecret:
        enabled: false
        # secretName: nameofsecret
        usernameKey: nextcloud-username
        passwordKey: nextcloud-password
      
  releaseName: next-cloud
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
