apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-cert
spec:
  secretName: mail-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - mail.blrobinson.uk
