apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mail-cert
  namespace: mail
spec:
  secretName: mail-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - home.blrobinson.uk
  - mail.home.blrobinson.uk
  # - mail.blrobinson.uk
