apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mail-public
spec:
  hostnames:
  - mail.blrobinson.uk
  parentRefs:
  - name: nginx-ingress
    namespace: ingress
    sectionName: https
  rules:
  - backendRefs:
    - name: mailu-front
      port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: mailu-front-tls
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: mailu-front
  validation:
    wellKnownCACertificates: System
    hostname: mail.blrobinson.uk
