apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-volume
  labels:
    volume: mail-volume
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/mail"