apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-volume
  labels:
    volume: mosquitto-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/mosquitto"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: mosquitto-volume
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: mosquitto-volume
