apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  selector:
    app.kubernetes.io/name: adguard
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.0.0.102
  ports:
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: http
      protocol: TCP
      port: 80
      targetport: 80

