apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alerts-config
  namespace: monitoring
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'telegram_receiver'
  receivers:
    - name: telegram_receiver
      telegramConfigs:
        - chatID: -4609103766
          botToken:
            key: token
            name: alertmanager-telegram-secret
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alerts
  namespace: monitoring
spec:
  replicas: 3
  alertmanagerConfiguration:
    name: alerts-config
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: alerts-web
  namespace: monitoring
spec:
  hostnames:
  - alertmanager.k8s.home.blrobinson.uk
  parentRefs:
  - name: gateway-ingress
    namespace: ingress
  rules:
  - backendRefs:
    - name: alertmanager-operated
      port: 9093
