apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: grafana
      version: '8.0.2'
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    serviceMonitor:
      enabled: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: Prometheus
          type: prometheus
          url: http://prometheus.monitoring.svc.cluster.local:9090
          editable: false
  releaseName: grafana
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana
spec:
  hostnames:
  - grafana.k8s.home.blrobinson.uk
  parentRefs:
  - name: gateway-ingress
    namespace: ingress
  rules:
  - backendRefs:
    - name: grafana
      port: 80
