namespace: monitoring

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/bundle.yaml
  - prometheus-rbac.yaml
  - prometheus.yaml
  - grafana.yaml
  - node-exporter.yaml
