apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        apiVersion: "v2"
        name: alertmanager-operated
        port: web
  nodeSelector:
    kubernetes.io/os: linux
  replicas: 3
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  ruleSelector:
    matchLabels:
      role: alerts
      prometheus: prometheus
  storage:
    volumeClaimTemplate:
        spec:
          selector:
            matchLabels:
              store: prometheus
          resources:
            requests:
              storage: 10Gi
  serviceAccountName: prometheus
  version: v2.22.1
  serviceMonitorSelector: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-store-0
  labels:
    store: prometheus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/prometheus/prometheus-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-store-1
  labels:
    store: prometheus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/prometheus/prometheus-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-store-2
  labels:
    store: prometheus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/prometheus/prometheus-2"
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
  sessionAffinity: ClientIP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: prometheus
spec:
  hostnames:
  - prometheus.k8s.home.blrobinson.uk
  parentRefs:
  - name: gateway-ingress
    namespace: ingress
  rules:
  - backendRefs:
    - name: prometheus
      port: 9090
