apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
spec:
  interval: 5m0s
  url: https://immich-app.github.io/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: immich
      version: '0.7.0'
      sourceRef:
        kind: HelmRepository
        name: immich
  values:
    immich:
      metrics:
        enabled: true
      persistence: # Need to look at this, its completely wrong currently
        library:
          existingClaim: immich-pvc
  releaseName: immich
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
