apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: immich
spec:
  interval: 5m0s
  url: https://immich-app.github.io/immich-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: immich
      version: '0.7.0'
      sourceRef:
        kind: HelmRepository
        name: immich
  values:
    image:
      tag: v1.113.0
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-pvc
    redis:
      enabled: true
      master:
        persistence:
          enabled: true
          existingClaim: immich-redis-master-pvc
    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            username: immich
            password: immich
            database: immich
      primary:
        readinessProbe:
          initialDelaySeconds: 60
        livenessProbe:
          initialDelaySeconds: 60
        persistence:
          enabled: true
          existingClaim: immich-postgres-pvc
  releaseName: immich
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
