apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-volume
  labels:
    volume: immich-volume
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/immich"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: immich-volume
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: immich-volume
