apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: container-registry
  namespace: container-registry
spec:
  issuerRef:
    name: letsencrypt
  dnsNames:
  - container-registry.k8s.home.blrobinson.uk