apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: container-registry
spec:
  replicas: 1
  selector:
    app: container-registry
  template:
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        # env:
        # - name: REGISTRY_HTTP_TLS_CERTIFICATE
        #   value: "/certs/tls.crt"
        # - name: REGISTRY_HTTP_TLS_KEY
        #   value: "/certs/tls.key"
        volumeMounts:
        # - name: registry-certs
        #   mountPath: "/certs"
        #   readOnly: true
        - name: registry-data
          mountPath: /var/lib/registry
      volumes:
      # - name: registry-certs
      #   secret:
      #     secretName: registry-cert
      - name: registry-data
        nfs:
          server: 10.0.0.11 # TODO MAKE DNS?
          path: /mnt/container-registry