apiVersion: v1
kind: Service
metadata:
  name: container-registry
  namespace: container-registry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: container-registry
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: container-registry
  namespace: container-registry
spec:
  addresses:
    - value: 10.0.0.100
  gatewayClassName: cilium
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: container-registry.k8s.home.blrobinson.uk
  - name: https
    port: 443
    protocol: HTTPS
    hostname: container-registry.k8s.home.blrobinson.uk
    tls:
      mode: Terminate
      certificateRefs:
        - name: "container-registry"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: container-registry
  namespace: container-registry
spec:
  parentRefs:
  - name: container-registry
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: container-registry
      port: 5000
