apiVersion: v1
kind: Service
metadata:
  name: container-registry
  namespace: container-registry
spec:
  selector:
    app.kubernetes.io/name: container-registry
  ports:
    - port: 5000
      protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: container-registry
  namespace: container-registry
spec:
  gatewayClassName: cilium
  listeners:
  - name: tcp
    port: 5000
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: TCPRoute
metadata:
  name: all-hosts
  namespace: container-registry
spec:
  parentRefs:
  - name: container-registry
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: container-registry
      port: 5000
