apiVersion: v1
kind: Service
metadata:
  name: container-registry
  namespace: container-registry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: container-registry
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: container-registry
  namespace: container-registry
spec:
  defaultBackend:
    service:
      name: container-registry
      port:
        number: 5000