apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.14.5'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    installCRDs: true
    config:
      featureGates:
        experimentalGatewayAPISupport: true
  releaseName: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benr@blrobinson.uk
    privateKeySecretRef:
      name: le-stage-pk
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            - name: cert-manager
              namespace: ingress
              kind: Gateway
