apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
spec:
  interval: 5m0s
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cert-manager
      version: '1.18.0'
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  values:
    installCRDs: true
    config:
      enableGatewayAPI: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
  releaseName: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
