apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-issuer
  namespace: flux-system
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: home-flux
    namespace: flux-system
  path: "./clusters/home/cert-manager/issuer"
  prune: true
  timeout: 1m