apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: foundry-vtt
  namespace: foundry
spec:
  interval: 5m0s
  url: https://hugoprudente.github.io/helm-charts/incubator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundry
  namespace: foundry
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: foundry-vtt
      version: '12.324.0'
      sourceRef:
        kind: HelmRepository
        name: foundry-vtt
  values:
    service:
      serviceType: ClusterIP
    image:
      tag: "12.331.0"
    container:
      version: "12.331.0"
      cache: "/data/Data/container_cache"
      preserveConfig: true
    foundryvtt:
      version: "12.331"
      hostname: "foundry.blrobinson.uk"
      licenseKey: true
    persistence:
      shared:
        enabled: true
        mounts:
          - containerPath: ""
            type: pvc
            claimName: "foundry-data-pvc"
          - containerPath: "/container_cache"
            type: pvc
            claimName: "foundry-container-cache-pvc"
        releaseName: foundry
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
