apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: foundry-vtt
spec:
  interval: 5m0s
  url: https://hugoprudente.github.io/helm-charts/incubator/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: foundry
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: foundry-vtt
      version: '0.2.14'
      sourceRef:
        kind: HelmRepository
        name: foundry-vtt
  values:
    persistance:
      storageClass: foundry
      dataDir:
        enabled: true
        size: 100Gi

  releaseName: foundry
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
