apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-data
  annotations:
    volume.beta.kubernetes.io/storage-class: default
  labels:
    volume: foundry-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/foundry"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-container-cache
  labels:
    volume: foundry-container-cache
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/foundry-container-cache"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-container-cache-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: foundry-container-cache
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: foundry-container-cache