apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry
  labels:
    volume: foundry
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/foundry"
