apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-data
  labels:
    volume: foundry-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/foundry"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: foundry-data
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: foundry-data
