apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-data
  labels:
    volume: foundry-data
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/foundry/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-data-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: foundry-data
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: foundry-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-shared
  labels:
    volume: foundry-shared
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/foundry/shared"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-shared-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: foundry-shared
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: foundry-shared
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foundry-assets
  labels:
    volume: foundry-assets
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.11
    path: "/mnt/foundry/assets"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundry-assets-pvc
spec:
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  volumeName: foundry-assets
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: foundry-assets