apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: benr@blrobinson.uk
    privateKeySecretRef:
      name: le-stage-pk
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
            # Has to be nginx-ingress as this is the public facing GW
            - name: nginx-ingress
              namespace: ingress
              kind: Gateway
            # Need the extra in order to make the local checks work
            - name: gateway-ingress
              namespace: ingress
              kind: Gateway
