apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-data
  labels:
    volume: open-webui-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/open-webui"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: open-webui-data
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: open-webui-data
