apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.10-10.0.1.254
  # Chosen as I have a separate network subnet configured on Unifi-SG for this range with DHCP disabled
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: unifi-router
spec:
  peerIP: 10.0.0.1
  asNumber: 64500
---
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: fa
  nodeMeshMaxRestartTime: 120s
  asNumber: 64500
  serviceClusterIPs:
    - cidr: 10.96.0.0/12
  serviceExternalIPs:
    - cidr: 10.0.1.1/24
  listenPort: 178
  bindMode: NodeIP
  communities:
    - name: bgp-large-community
      value: 64500:300:100
  prefixAdvertisements:
    - cidr: 10.0.1.1/2
      communities:
        - bgp-large-community
        - 64500:120

# configure
# set protocols bgp 64501 parameters router-id 10.0.0.1
# set protocols bgp 64501 neighbor 10.0.0.20 remote-as 64500
# set protocols bgp 64501 neighbor 10.0.0.21 remote-as 64500
# set protocols bgp 64501 neighbor 10.0.0.22 remote-as 64500
# commit
# save
# exit

# calicoctl patch bgpconfiguration default -p '{"spec": {"asNumber": "64500"}}'

