apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.10-10.0.1.254
  # Chosen as I have a separate network subnet configured on Unifi-SG for this range with DHCP disabled
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: unifi-router
spec:
  peerIP: 10.0.0.1
  asNumber: 64500

# configure
# set protocols bgp 64501 parameters router-id 10.0.0.1
# set protocols bgp 64501 neighbor 10.0.0.20 remote-as 64500
# commit
# save
# exit
