apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 10.0.0.100-10.0.0.254
  # In order for L2Advertisement to work this must be in the same network range as the local network.
  # Unifi configures 10.0.0.1/23 then DHCP range from 10.0.1.1-10.0.1.254
  # Static IPs are generally assigned below 10.0.0.100 (see DNS server config)
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
