apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.1.10-10.0.1.254
  # Chosen as I have a separate network subnet configured on Unifi-SG for this range with DHCP disabled
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: unifi
  namespace: metallb-system
spec:
  myASN: 64500
  peerASN: 64501
  peerAddress: 10.0.0.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advert
  namespace: metallb-system