apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  - 10.0.3.0/24
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: second-pool
  namespace: metallb-system
spec:
  autoAssign: false
  addresses:
  -  2a06:61c2:27ae:2::/64
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: unifi-gateway
  namespace: metallb-system
spec:
  dualStackAddressFamily: true
  myASN: 65001
  peerASN: 65000
  peerAddress: 10.0.0.1
  peerPort: 179
  holdTime: 120s
  keepaliveTime: 40s
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: ipv4-bgp
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: ipv6-bgp
  namespace: metallb-system
spec:
  ipAddressPools:
  - second-pool
