apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 5m0s
  url: https://headlamp-k8s.github.io/headlamp/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      version: "0.25.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
    requests:
        cpu: "150m"
        memory: "128Mi"
    limits:
      cpu: "150m"
      memory: "128Mi"
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
