---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-access-dns
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["get", "patch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-dns
subjects:
- kind: ServiceAccount
  name: dns-deployment-access
  namespace: github-arc
roleRef:
  kind: Role
  name: deploy-access-dns
  apiGroup: rbac.authorization.k8s.io
