---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-access-dns
rules:
- apiGroups: ["kustomize.toolkit.fluxcd.io", "apps"]
  resources: ["kustomizations", "deployments", "replicasets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-dns
subjects:
- kind: ServiceAccount
  name: dns-deployment-access
  namespace: github-arc
roleRef:
  kind: Role
  name: deploy-access-dns
  apiGroup: rbac.authorization.k8s.io
