apiVersion: v1
kind: Service
metadata:
  name: dns
spec:
  selector:
    app.kubernetes.io/name: dns
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.0.3.103
  ports:
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: dns-v6
spec:
  selector:
    app.kubernetes.io/name: dns
  type: LoadBalancer
  ipFamilies:
    - IPv6
  ipFamilyPolicy: SingleStack
  externalTrafficPolicy: Cluster
  loadBalancerIP: 2a06:61c2:27ae:2::1
  ports:
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
