apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: dns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dns
  ports:
    - port: 53
      targetPort: 53
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: dns
  namespace: dns
spec:
  addresses:
    - value: 10.0.0.102
  gatewayClassName: cilium
  listeners:
  - name: tcp
    port: 53
    protocol: TCP
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tcp-dns
spec:
  parentRefs:
  - name: dns
    sectionName: tcp
  rules:
  - backendRefs:
    - name: dns
      port: 53
