apiVersion: v1
kind: Service
metadata:
  name: dns
  namespace: dns
spec:
  selector:
    app.kubernetes.io/name: dns
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.0.0.103
  ports:
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
