apiVersion: v1
kind: ServiceAccount
metadata:
  name: mail-deployment-access
  namespace: github-arc
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: docker-mail-runners
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: '0.9.3'
      sourceRef:
        kind: HelmRepository
        name: arc
  values:
    githubConfigSecret: git-token
    githubConfigUrl: "https://github.com/bl-robinson/docker-mail"
    containerMode:
      type: dind
    template:
      spec:
        serviceAccountName: mail-deployment-access
  releaseName: docker-mail-runners
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3