apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: arc
spec:
  interval: 5m0s
  type: oci
  url: oci://ghcr.io/actions/actions-runner-controller-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: '0.11.0'
      sourceRef:
        kind: HelmRepository
        name: arc
  values:
    githubConfigSecret: git-token
  releaseName: arc
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
