apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-volume
  labels:
    volume: vaultwarden-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.3
    path: "/data/vaultwarden"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  volumeName: vaultwarden-volume
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: vaultwarden-volume
