apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  controlNamespace: logging
  fluentd:
    disablePvc: true
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: logging-agent
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: clusterflow
spec:
  globalOutputRefs:
    - loki-output
  match:
    - select: {}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: loki-output
spec:
  loki:
    configure_kubernetes_labels: true
    drop_single_key: false
    extract_kubernetes_labels: true
    url: http://loki-gateway.logging.svc.cluster.local
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
