apiVersion: v1
kind: Namespace
metadata:
  name: dns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dns
  namespace: dns
spec:
  interval: 10m
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: home-flux
    namespace: flux-system
  path: "./clusters/home/dns"
  prune: true
  timeout: 1m
