apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metallb.yaml
  - container-registry.yaml
  - dns.yaml
  - cert-manager.yaml
  - web-ingress.yaml
  - adguard.yaml
  - unifi.yaml
  - monitoring.yaml
  - github-arc.yaml
  - shell.yaml
  # - immich.yaml
  # - mail.yaml
