apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metallb.yaml
  - container-registry.yaml
  - dns.yaml
  - cert-manager.yaml
  - web-ingress.yaml
  - adguard.yaml
  - monitoring.yaml
  - github-arc.yaml
  - shell.yaml
  - logging.yaml
  - immich.yaml # Look at https://github.com/immich-app/immich-charts/blob/main/charts/immich/Chart.yaml for setting up persistence for psql/redis
  - mail.yaml
  - foundry.yaml
