apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metal-lb
  namespace: flux-system
spec:
  interval: 2m
  sourceRef:
    kind: GitRepository
    name: home-flux
  path: "./clusters/home/metallb"
  prune: true
  timeout: 1m