apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress
  namespace: default
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/nginxinc/charts/nginx-ingress
  version: 1.2.0
