apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-ingress
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.0.0.101
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: main-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-cert
spec:
  secretName: main-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - container-registry.k8s.home.blrobinson.uk
  - prometheus.k8s.home.blrobinson.uk
  - grafana.k8s.home.blrobinson.uk
