apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      metallb.universe.tf/loadBalancerIPs: 10.0.3.100,2a06:61c2:27ae:2::3
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-passthrough
      protocol: TLS
      port: 443
      tls:
        mode: Passthrough
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-ingress-http
  namespace: ingress
spec:
  parentRefs:
    - name: nginx-ingress
      sectionName: http
  rules:
    - backendRefs:
        - name: web
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: nginx-ingress-tls
  namespace: ingress
spec:
  parentRefs:
    - name: nginx-ingress
      sectionName: https-passthrough
  rules:
    - backendRefs:
        - name: web
          port: 443
