apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ingress
  type: ClusterIP
  selector:
    app.kubernetes.io/name:web
  ports:
    - port: 443
      targetPort: 443
    - port: 80
      targetPort: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: web-ingress
  namespace: ingress
spec:
  gatewayClassName: cilium
  addresses:
    - value: 10.0.0.101
  listeners:
    - name: http
      protocol: HTTP
      port: 80
    - name: https
      protocol: TLS
      port: 443
      tls:
        mode: Passthrough
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: web-ingress-tls
  namespace: ingress
spec:
  parentRefs:
  - name: web-ingress
  rules:
    - backendRefs:
      - name: web
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: web-ingress-http
  namespace: ingress
spec:
  parentRefs:
    - name: web-ingress
  rules:
    - matches:
      backendRefs:
      - name: web
        port: 80
