apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ingress
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80