apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web
    spec:
      containers:
      - name: web
        image: container-registry.k8s.home.blrobinson.uk/docker-web:latest
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
          - name: public-cert
            mountPath: /etc/cert
            readOnly: true
          - name: screenshots
            mountPath: /var/www/vhosts/screenshots
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
      volumes:
        - name: public-cert
          secret:
            secretName: public-cert
        - name: screenshots
          nfs:
            server: 10.0.0.11 # TODO MAKE DNS?
            path: /mnt/screenshots
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: web
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-cert
spec:
  secretName: public-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
  - unifi.blrobinson.uk
  - adguard.blrobinson.uk
  - grabs.blrobinson.uk
  - mail.blrobinson.uk
  - immich.blrobinson.uk
  - shed-cam.blrobinson.uk
  - foundry.blrobinson.uk
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nginx-ingress-http
spec:
  parentRefs:
  - name: nginx-ingress
    kind: Gateway
    sectionName: http
  rules:
  - backendRefs:
      - name: web
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: nginx-ingress-https
  namespace: ingress
spec:
  parentRefs:
  - name: nginx-ingress
    kind: Gateway
    sectionName: https
  rules:
    - backendRefs:
      - name: web
        port: 443
