apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh
  labels:
    app.kubernetes.io/name: ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ssh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ssh
    spec:
      containers:
      - name: ssh
        image: lscr.io/linuxserver/openssh-server:version-9.7_p1-r4
        ports:
        - containerPort: 2222
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: USER_NAME
          value: "benr"
        - name: PASSWORD_ACCESS
          value: "false"
        - name: SUDO_ACCESS
          value: "false"
        - name: PUBLIC_KEY
          value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3STIAhGO45ksAputEJh/g7QtXljdRC+gF5kgtUjDpSOkNdgx9n6ciizXCm2VmZhGrBt2mqSekO21CCfu7VIq9nK7/TQ2PowyYtzFzfzUpts5S5RPBoUKgbdShoR2sIxi9dFblYBPv7XzHle8XzBZ7/zTEBj9fHAaQic/2rojzv6OGuPYzL480Ee2XgwTLcjoYw44PT751O+QiRyh2ONYrMA7hfZAODTht77LNXj39wBJdoE2wfKfkbntxc/jmewr7GrRqywz3HbDr33L7f4zEyCgepQ79UKd6IWUFpFf9FZ+/QQz/hoaGtA8ypcP3QdvoSJPxYCi8AvOP5h0EWvQl benr@wall-e"
        - name: LOG_STDOUT
          value: "true"
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
        # securityContext:
        #   allowPrivilegeEscalation: false
        #   readOnlyRootFilesystem: true
        #   runAsNonRoot: true
        #   runAsUser: 1000
        volumeMounts:
          - name: screenshots
            mountPath: /config/screenshots
      volumes:
      - name: screenshots
        nfs:
          server: 10.0.0.3 # TODO MAKE DNS?
          path: /data/screenshots
