apiVersion: v1
kind: Service
metadata:
  name: ssh
spec:
  selector:
    app.kubernetes.io/name: ssh
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.0.0.103
  ports:
    - name: tcp
      protocol: TCP
      port: 22
      targetPort: 2222
